version: '3'
services:
  react:
    container_name: react
    stdin_open: true
    tty: true
    build: ./frontend
    ports:
      - '3000:3000'
    links:
      - node
    networks:
      - mern-app
  node:
    container_name: node
    restart: always
    build: ./backend
    ports:
      - '4000:4000'
    links:
      - mongo
    environment:
      TWILIO_ACCOUNT_SID: '${TWILIO_ACCOUNT_SID}'
      TWILIO_AUTH_TOKEN: '${TWILIO_AUTH_TOKEN}'
      TWILIO_PHONE_NUMBER: '${TWILIO_PHONE_NUMBER}'
    networks:
      - mern-app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    networks:
      - mern-app
volumes:
  mongodata:
networks:
  mern-app:
    driver: bridge
