version: '3'
services:
  react:
    container_name: react
    stdin_open: true
    tty: true
    build: ./frontend
    ports:
      - '3000:3000'
    links:
      - node
    networks:
      - mern-app
  node:
    container_name: node
    restart: always
    build: ./backend
    ports:
      - '8080:8080'
    environment:
      TWILIO_ACCOUNT_SID: '${TWILIO_ACCOUNT_SID}'
      TWILIO_AUTH_TOKEN: '${TWILIO_AUTH_TOKEN}'
      TWILIO_PHONE_NUMBER: '${TWILIO_PHONE_NUMBER}'
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
