FROM node:16-alpine3.11

WORKDIR /usr/src/app

COPY package.json /usr/src/app

RUN npm install

ENV TWILIO_ACCOUNT_SID = "${TWILIO_ACCOUNT_SID}"
ENV TWILIO_AUTH_TOKEN = "${TWILIO_AUTH_TOKEN}"
ENV TWILIO_PHONE_NUMBER = "${TWILIO_PHONE_NUMBER}" 

COPY . /usr/src/app

EXPOSE 8080

CMD ["npm", "start"]